// Auto-generated precomputed ruleset data (Local files only)
export interface PrecomputedRuleset {
  id: string;
  name: string;
  linkUrl: string;
  homeUrl: string;
  content: string;
  metrics: {
    words: number;
    characters: number;
    uniqueWordCount: number;
    wordSet: string[];
    wordCounts: Record<string, number>;
  };
}

export const PRECOMPUTED_RULESETS: PrecomputedRuleset[] = [
  {
    "id": "original",
    "name": "Original",
    "linkUrl": "https://legacy.earlham.edu/~peters/writing/nomic.htm#initial%20set",
    "homeUrl": "#",
    "content": "Initial Set of Rules\nImmutable Rules\n101. All players must always abide by all the rules then in effect, in the form in which they are then in effect. The rules in the Initial Set are in effect whenever a game begins. The Initial Set consists of Rules 101-116 (immutable) and 201-213 (mutable).\n\n*\n102. Initially rules in the 100's are immutable and rules in the 200's are mutable. Rules subsequently enacted or transmuted (that is, changed from immutable to mutable or vice versa) may be immutable or mutable regardless of their numbers, and rules in the Initial Set may be transmuted regardless of their numbers.\n\n*\n103. A rule-change is any of the following: (1) the enactment, repeal, or amendment of a mutable rule; (2) the enactment, repeal, or amendment of an amendment of a mutable rule; or (3) the transmutation of an immutable rule into a mutable rule or vice versa.\n\n(Note: This definition implies that, at least initially, all new rules are mutable; immutable rules, as long as they are immutable, may not be amended or repealed; mutable rules, as long as they are mutable, may be amended or repealed; any rule of any status may be transmuted; no rule is absolutely immune to change.)\n\n*\n104. All rule-changes proposed in the proper way shall be voted on. They will be adopted if and only if they receive the required number of votes.\n\n*\n105. Every player is an eligible voter. Every eligible voter must participate in every vote on rule-changes.\n\n*\n106. All proposed rule-changes shall be written down before they are voted on. If they are adopted, they shall guide play in the form in which they were voted on.\n\n*\n107. No rule-change may take effect earlier than the moment of the completion of the vote that adopted it, even if its wording explicitly states otherwise. No rule-change may have retroactive application.\n\n*\n108. Each proposed rule-change shall be given a number for reference. The numbers shall begin with 301, and each rule-change proposed in the proper way shall receive the next successive integer, whether or not the proposal is adopted.\n\nIf a rule is repealed and reenacted, it receives the number of the proposal to reenact it. If a rule is amended or transmuted, it receives the number of the proposal to amend or transmute it. If an amendment is amended or repealed, the entire rule of which it is a part receives the number of the proposal to amend or repeal the amendment.\n\n*\n109. Rule-changes that transmute immutable rules into mutable rules may be adopted if and only if the vote is unanimous among the eligible voters. Transmutation shall not be implied, but must be stated explicitly in a proposal to take effect.\n\n*\n110. In a conflict between a mutable and an immutable rule, the immutable rule takes precedence and the mutable rule shall be entirely void. For the purposes of this rule a proposal to transmute an immutable rule does not \"conflict\" with that immutable rule.\n\n*\n111. If a rule-change as proposed is unclear, ambiguous, paradoxical, or destructive of play, or if it arguably consists of two or more rule-changes compounded or is an amendment that makes no difference, or if it is otherwise of questionable value, then the other players may suggest amendments or argue against the proposal before the vote. A reasonable time must be allowed for this debate. The proponent decides the final form in which the proposal is to be voted on and, unless the Judge has been asked to do so, also decides the time to end debate and vote.\n\n*\n112. The state of affairs that constitutes winning may not be altered from achieving n points to any other state of affairs. The magnitude of n and the means of earning points may be changed, and rules that establish a winner when play cannot continue may be enacted and (while they are mutable) be amended or repealed.\n\n*\n113. A player always has the option to forfeit the game rather than continue to play or incur a game penalty. No penalty worse than losing, in the judgment of the player to incur it, may be imposed.\n\n*\n114. There must always be at least one mutable rule. The adoption of rule-changes must never become completely impermissible.\n\n*\n115. Rule-changes that affect rules needed to allow or apply rule-changes are as permissible as other rule-changes. Even rule-changes that amend or repeal their own authority are permissible. No rule-change or type of move is impermissible solely on account of the self-reference or self-application of a rule.\n\n*\n116. Whatever is not prohibited or regulated by a rule is permitted and unregulated, with the sole exception of changing the rules, which is permitted only when a rule or set of rules explicitly or implicitly permits it.\n\n*\nMutable Rules\n201. Players shall alternate in clockwise order, taking one whole turn apiece. Turns may not be skipped or passed, and parts of turns may not be omitted. All players begin with zero points.\n\nIn mail and computer games, players shall alternate in alphabetical order by surname.\n\n*\n202. One turn consists of two parts in this order: (1) proposing one rule-change and having it voted on, and (2) throwing one die once and adding the number of points on its face to one's score.\n\nIn mail and computer games, instead of throwing a die, players subtract 291 from the ordinal number of their proposal and multiply the result by the fraction of favorable votes it received, rounded to the nearest integer. (This yields a number between 0 and 10 for the first player, with the upper limit increasing by one each turn; more points are awarded for more popular proposals.)\n\n*\n203. A rule-change is adopted if and only if the vote is unanimous among the eligible voters. If this rule is not amended by the end of the second complete circuit of turns, it automatically changes to require only a simple majority.\n\n*\n204. If and when rule-changes can be adopted without unanimity, the players who vote against winning proposals shall receive 10 points each.\n\n*\n205. An adopted rule-change takes full effect at the moment of the completion of the vote that adopted it.\n\n*\n206. When a proposed rule-change is defeated, the player who proposed it loses 10 points.\n\n*\n207. Each player always has exactly one vote.\n\n*\n208. The winner is the first player to achieve 100 (positive) points.\n\nIn mail and computer games, the winner is the first player to achieve 200 (positive) points.\n\n*\n209. At no time may there be more than 25 mutable rules.\n\n*\n210. Players may not conspire or consult on the making of future rule-changes unless they are team-mates.\n\nThe first paragraph of this rule does not apply to games by mail or computer.\n\n*\n211. If two or more mutable rules conflict with one another, or if two or more immutable rules conflict with one another, then the rule with the lowest ordinal number takes precedence.\n\nIf at least one of the rules in conflict explicitly says of itself that it defers to another rule (or type of rule) or takes precedence over another rule (or type of rule), then such provisions shall supersede the numerical method for determining precedence.\n\nIf two or more rules claim to take precedence over one another or to defer to one another, then the numerical method again governs.\n\n*\n212. If players disagree about the legality of a move or the interpretation or application of a rule, then the player preceding the one moving is to be the Judge and decide the question. Disagreement for the purposes of this rule may be created by the insistence of any player. This process is called invoking Judgment.\n\nWhen Judgment has been invoked, the next player may not begin his or her turn without the consent of a majority of the other players.\n\nThe Judge's Judgment may be overruled only by a unanimous vote of the other players taken before the next turn is begun. If a Judge's Judgment is overruled, then the player preceding the Judge in the playing order becomes the new Judge for the question, and so on, except that no player is to be Judge during his or her own turn or during the turn of a team-mate.\n\nUnless a Judge is overruled, one Judge settles all questions arising from the game until the next turn is begun, including questions as to his or her own legitimacy and jurisdiction as Judge.\n\nNew Judges are not bound by the decisions of old Judges. New Judges may, however, settle only those questions on which the players currently disagree and that affect the completion of the turn in which Judgment was invoked. All decisions by Judges shall be in accordance with all the rules then in effect; but when the rules are silent, inconsistent, or unclear on the point at issue, then the Judge shall consider game-custom and the spirit of the game before applying other standards.\n\n*\n213. If the rules are changed so that further play is impossible, or if the legality of a move cannot be determined with finality, or if by the Judge's best reasoning, not overruled, a move appears equally legal and illegal, then the first player unable to complete a turn is the winner.\n\nThis rule takes precedence over every other rule determining the winner.",
    "metrics": {
      "words": 1582,
      "characters": 9055,
      "uniqueWordCount": 424,
      "wordSet": [
        "initial",
        "set",
        "of",
        "rules",
        "immutable",
        "101",
        "all",
        "players",
        "must",
        "always",
        "abide",
        "by",
        "the",
        "then",
        "in",
        "effect",
        "form",
        "which",
        "they",
        "are",
        "whenever",
        "a",
        "game",
        "begins",
        "consists",
        "101116",
        "and",
        "201213",
        "mutable",
        "102",
        "initially",
        "100s",
        "200s",
        "subsequently",
        "enacted",
        "or",
        "transmuted",
        "that",
        "is",
        "changed",
        "from",
        "to",
        "vice",
        "versa",
        "may",
        "be",
        "regardless",
        "their",
        "numbers",
        "103",
        "rulechange",
        "any",
        "following",
        "1",
        "enactment",
        "repeal",
        "amendment",
        "rule",
        "2",
        "an",
        "3",
        "transmutation",
        "into",
        "note",
        "this",
        "definition",
        "implies",
        "at",
        "least",
        "new",
        "as",
        "long",
        "not",
        "amended",
        "repealed",
        "status",
        "no",
        "absolutely",
        "immune",
        "change",
        "104",
        "rulechanges",
        "proposed",
        "proper",
        "way",
        "shall",
        "voted",
        "on",
        "will",
        "adopted",
        "if",
        "only",
        "receive",
        "required",
        "number",
        "votes",
        "105",
        "every",
        "player",
        "eligible",
        "voter",
        "participate",
        "vote",
        "106",
        "written",
        "down",
        "before",
        "guide",
        "play",
        "were",
        "107",
        "take",
        "earlier",
        "than",
        "moment",
        "completion",
        "it",
        "even",
        "its",
        "wording",
        "explicitly",
        "states",
        "otherwise",
        "have",
        "retroactive",
        "application",
        "108",
        "each",
        "given",
        "for",
        "reference",
        "begin",
        "with",
        "301",
        "next",
        "successive",
        "integer",
        "whether",
        "proposal",
        "reenacted",
        "receives",
        "reenact",
        "amend",
        "transmute",
        "entire",
        "part",
        "109",
        "unanimous",
        "among",
        "voters",
        "implied",
        "but",
        "stated",
        "110",
        "conflict",
        "between",
        "takes",
        "precedence",
        "entirely",
        "void",
        "purposes",
        "does",
        "111",
        "unclear",
        "ambiguous",
        "paradoxical",
        "destructive",
        "arguably",
        "two",
        "more",
        "compounded",
        "makes",
        "difference",
        "questionable",
        "value",
        "other",
        "suggest",
        "amendments",
        "argue",
        "against",
        "reasonable",
        "time",
        "allowed",
        "debate",
        "proponent",
        "decides",
        "final",
        "unless",
        "judge",
        "has",
        "been",
        "asked",
        "do",
        "so",
        "also",
        "end",
        "112",
        "state",
        "affairs",
        "constitutes",
        "winning",
        "altered",
        "achieving",
        "n",
        "points",
        "magnitude",
        "means",
        "earning",
        "establish",
        "winner",
        "when",
        "cannot",
        "continue",
        "while",
        "113",
        "option",
        "forfeit",
        "rather",
        "incur",
        "penalty",
        "worse",
        "losing",
        "judgment",
        "imposed",
        "114",
        "there",
        "one",
        "adoption",
        "never",
        "become",
        "completely",
        "impermissible",
        "115",
        "affect",
        "needed",
        "allow",
        "apply",
        "permissible",
        "own",
        "authority",
        "type",
        "move",
        "solely",
        "account",
        "selfreference",
        "selfapplication",
        "116",
        "whatever",
        "prohibited",
        "regulated",
        "permitted",
        "unregulated",
        "sole",
        "exception",
        "changing",
        "implicitly",
        "permits",
        "201",
        "alternate",
        "clockwise",
        "order",
        "taking",
        "whole",
        "turn",
        "apiece",
        "turns",
        "skipped",
        "passed",
        "parts",
        "omitted",
        "zero",
        "mail",
        "computer",
        "games",
        "alphabetical",
        "surname",
        "202",
        "proposing",
        "having",
        "throwing",
        "die",
        "once",
        "adding",
        "face",
        "ones",
        "score",
        "instead",
        "subtract",
        "291",
        "ordinal",
        "multiply",
        "result",
        "fraction",
        "favorable",
        "received",
        "rounded",
        "nearest",
        "yields",
        "0",
        "10",
        "first",
        "upper",
        "limit",
        "increasing",
        "awarded",
        "popular",
        "proposals",
        "203",
        "second",
        "complete",
        "circuit",
        "automatically",
        "changes",
        "require",
        "simple",
        "majority",
        "204",
        "can",
        "without",
        "unanimity",
        "who",
        "205",
        "full",
        "206",
        "defeated",
        "loses",
        "207",
        "exactly",
        "208",
        "achieve",
        "100",
        "positive",
        "200",
        "209",
        "25",
        "210",
        "conspire",
        "consult",
        "making",
        "future",
        "teammates",
        "paragraph",
        "211",
        "another",
        "lowest",
        "says",
        "itself",
        "defers",
        "over",
        "such",
        "provisions",
        "supersede",
        "numerical",
        "method",
        "determining",
        "claim",
        "defer",
        "again",
        "governs",
        "212",
        "disagree",
        "about",
        "legality",
        "interpretation",
        "preceding",
        "moving",
        "decide",
        "question",
        "disagreement",
        "created",
        "insistence",
        "process",
        "called",
        "invoking",
        "invoked",
        "his",
        "her",
        "consent",
        "judges",
        "overruled",
        "taken",
        "begun",
        "playing",
        "becomes",
        "except",
        "during",
        "teammate",
        "settles",
        "questions",
        "arising",
        "until",
        "including",
        "legitimacy",
        "jurisdiction",
        "bound",
        "decisions",
        "old",
        "however",
        "settle",
        "those",
        "currently",
        "was",
        "accordance",
        "silent",
        "inconsistent",
        "point",
        "issue",
        "consider",
        "gamecustom",
        "spirit",
        "applying",
        "standards",
        "213",
        "further",
        "impossible",
        "determined",
        "finality",
        "best",
        "reasoning",
        "appears",
        "equally",
        "legal",
        "illegal",
        "unable"
      ],
      "wordCounts": {
        "0": 1,
        "1": 2,
        "2": 2,
        "3": 1,
        "10": 3,
        "25": 1,
        "100": 1,
        "101": 1,
        "102": 1,
        "103": 1,
        "104": 1,
        "105": 1,
        "106": 1,
        "107": 1,
        "108": 1,
        "109": 1,
        "110": 1,
        "111": 1,
        "112": 1,
        "113": 1,
        "114": 1,
        "115": 1,
        "116": 1,
        "200": 1,
        "201": 1,
        "202": 1,
        "203": 1,
        "204": 1,
        "205": 1,
        "206": 1,
        "207": 1,
        "208": 1,
        "209": 1,
        "210": 1,
        "211": 1,
        "212": 1,
        "213": 1,
        "291": 1,
        "301": 1,
        "101116": 1,
        "201213": 1,
        "initial": 4,
        "set": 5,
        "of": 60,
        "rules": 27,
        "immutable": 14,
        "all": 9,
        "players": 12,
        "must": 6,
        "always": 4,
        "abide": 1,
        "by": 12,
        "the": 119,
        "then": 11,
        "in": 29,
        "effect": 7,
        "form": 3,
        "which": 7,
        "they": 11,
        "are": 17,
        "whenever": 1,
        "a": 36,
        "game": 5,
        "begins": 1,
        "consists": 3,
        "and": 32,
        "mutable": 18,
        "initially": 2,
        "100s": 1,
        "200s": 1,
        "subsequently": 1,
        "enacted": 2,
        "or": 49,
        "transmuted": 4,
        "that": 15,
        "is": 33,
        "changed": 3,
        "from": 4,
        "to": 29,
        "vice": 2,
        "versa": 2,
        "may": 21,
        "be": 31,
        "regardless": 2,
        "their": 4,
        "numbers": 3,
        "rulechange": 11,
        "any": 5,
        "following": 1,
        "enactment": 2,
        "repeal": 4,
        "amendment": 6,
        "rule": 30,
        "an": 8,
        "transmutation": 2,
        "into": 2,
        "note": 1,
        "this": 10,
        "definition": 1,
        "implies": 1,
        "at": 6,
        "least": 3,
        "new": 4,
        "as": 9,
        "long": 2,
        "not": 14,
        "amended": 6,
        "repealed": 5,
        "status": 1,
        "no": 8,
        "absolutely": 1,
        "immune": 1,
        "change": 1,
        "rulechanges": 12,
        "proposed": 7,
        "proper": 2,
        "way": 2,
        "shall": 14,
        "voted": 5,
        "on": 12,
        "will": 1,
        "adopted": 9,
        "if": 25,
        "only": 7,
        "receive": 3,
        "required": 1,
        "number": 9,
        "votes": 2,
        "every": 4,
        "player": 14,
        "eligible": 4,
        "voter": 2,
        "participate": 1,
        "vote": 10,
        "written": 1,
        "down": 1,
        "before": 4,
        "guide": 1,
        "play": 5,
        "were": 1,
        "take": 3,
        "earlier": 1,
        "than": 4,
        "moment": 2,
        "completion": 3,
        "it": 16,
        "even": 2,
        "its": 2,
        "wording": 1,
        "explicitly": 4,
        "states": 1,
        "otherwise": 2,
        "have": 1,
        "retroactive": 1,
        "application": 2,
        "each": 5,
        "given": 1,
        "for": 8,
        "reference": 1,
        "begin": 3,
        "with": 10,
        "next": 4,
        "successive": 1,
        "integer": 2,
        "whether": 1,
        "proposal": 9,
        "reenacted": 1,
        "receives": 3,
        "reenact": 1,
        "amend": 3,
        "transmute": 3,
        "entire": 1,
        "part": 1,
        "unanimous": 3,
        "among": 2,
        "voters": 2,
        "implied": 1,
        "but": 2,
        "stated": 1,
        "conflict": 5,
        "between": 2,
        "takes": 5,
        "precedence": 6,
        "entirely": 1,
        "void": 1,
        "purposes": 2,
        "does": 2,
        "unclear": 2,
        "ambiguous": 1,
        "paradoxical": 1,
        "destructive": 1,
        "arguably": 1,
        "two": 5,
        "more": 7,
        "compounded": 1,
        "makes": 1,
        "difference": 1,
        "questionable": 1,
        "value": 1,
        "other": 7,
        "suggest": 1,
        "amendments": 1,
        "argue": 1,
        "against": 2,
        "reasonable": 1,
        "time": 3,
        "allowed": 1,
        "debate": 2,
        "proponent": 1,
        "decides": 2,
        "final": 1,
        "unless": 3,
        "judge": 9,
        "has": 4,
        "been": 2,
        "asked": 1,
        "do": 1,
        "so": 3,
        "also": 1,
        "end": 2,
        "state": 2,
        "affairs": 2,
        "constitutes": 1,
        "winning": 2,
        "altered": 1,
        "achieving": 1,
        "n": 2,
        "points": 9,
        "magnitude": 1,
        "means": 1,
        "earning": 1,
        "establish": 1,
        "winner": 5,
        "when": 6,
        "cannot": 2,
        "continue": 2,
        "while": 1,
        "option": 1,
        "forfeit": 1,
        "rather": 1,
        "incur": 2,
        "penalty": 2,
        "worse": 1,
        "losing": 1,
        "judgment": 6,
        "imposed": 1,
        "there": 2,
        "one": 14,
        "adoption": 1,
        "never": 1,
        "become": 1,
        "completely": 1,
        "impermissible": 2,
        "affect": 2,
        "needed": 1,
        "allow": 1,
        "apply": 2,
        "permissible": 2,
        "own": 3,
        "authority": 1,
        "type": 3,
        "move": 4,
        "solely": 1,
        "account": 1,
        "selfreference": 1,
        "selfapplication": 1,
        "whatever": 1,
        "prohibited": 1,
        "regulated": 1,
        "permitted": 2,
        "unregulated": 1,
        "sole": 1,
        "exception": 1,
        "changing": 1,
        "implicitly": 1,
        "permits": 1,
        "alternate": 2,
        "clockwise": 1,
        "order": 4,
        "taking": 1,
        "whole": 1,
        "turn": 10,
        "apiece": 1,
        "turns": 3,
        "skipped": 1,
        "passed": 1,
        "parts": 2,
        "omitted": 1,
        "zero": 1,
        "mail": 4,
        "computer": 4,
        "games": 4,
        "alphabetical": 1,
        "surname": 1,
        "proposing": 1,
        "having": 1,
        "throwing": 2,
        "die": 2,
        "once": 1,
        "adding": 1,
        "face": 1,
        "ones": 1,
        "score": 1,
        "instead": 1,
        "subtract": 1,
        "ordinal": 2,
        "multiply": 1,
        "result": 1,
        "fraction": 1,
        "favorable": 1,
        "received": 1,
        "rounded": 1,
        "nearest": 1,
        "yields": 1,
        "first": 5,
        "upper": 1,
        "limit": 1,
        "increasing": 1,
        "awarded": 1,
        "popular": 1,
        "proposals": 2,
        "second": 1,
        "complete": 2,
        "circuit": 1,
        "automatically": 1,
        "changes": 1,
        "require": 1,
        "simple": 1,
        "majority": 2,
        "can": 1,
        "without": 2,
        "unanimity": 1,
        "who": 2,
        "full": 1,
        "defeated": 1,
        "loses": 1,
        "exactly": 1,
        "achieve": 2,
        "positive": 2,
        "conspire": 1,
        "consult": 1,
        "making": 1,
        "future": 1,
        "teammates": 1,
        "paragraph": 1,
        "another": 6,
        "lowest": 1,
        "says": 1,
        "itself": 1,
        "defers": 1,
        "over": 3,
        "such": 1,
        "provisions": 1,
        "supersede": 1,
        "numerical": 2,
        "method": 2,
        "determining": 2,
        "claim": 1,
        "defer": 1,
        "again": 1,
        "governs": 1,
        "disagree": 2,
        "about": 1,
        "legality": 2,
        "interpretation": 1,
        "preceding": 2,
        "moving": 1,
        "decide": 1,
        "question": 2,
        "disagreement": 1,
        "created": 1,
        "insistence": 1,
        "process": 1,
        "called": 1,
        "invoking": 1,
        "invoked": 2,
        "his": 3,
        "her": 3,
        "consent": 1,
        "judges": 7,
        "overruled": 4,
        "taken": 1,
        "begun": 2,
        "playing": 1,
        "becomes": 1,
        "except": 1,
        "during": 2,
        "teammate": 1,
        "settles": 1,
        "questions": 3,
        "arising": 1,
        "until": 1,
        "including": 1,
        "legitimacy": 1,
        "jurisdiction": 1,
        "bound": 1,
        "decisions": 2,
        "old": 1,
        "however": 1,
        "settle": 1,
        "those": 1,
        "currently": 1,
        "was": 1,
        "accordance": 1,
        "silent": 1,
        "inconsistent": 1,
        "point": 1,
        "issue": 1,
        "consider": 1,
        "gamecustom": 1,
        "spirit": 1,
        "applying": 1,
        "standards": 1,
        "further": 1,
        "impossible": 1,
        "determined": 1,
        "finality": 1,
        "best": 1,
        "reasoning": 1,
        "appears": 1,
        "equally": 1,
        "legal": 1,
        "illegal": 1,
        "unable": 1
      }
    }
  }
];
