// Auto-generated precomputed ruleset data (Local files only)
export interface PrecomputedRuleset {
  id: string;
  name: string;
  linkUrl: string;
  homeUrl: string;
  content: string;
  metrics: {
    words: number;
    characters: number;
    uniqueWordCount: number;
    wordSet: string[];
    wordCounts: Record<string, number>;
  };
}

export const PRECOMPUTED_RULESETS: PrecomputedRuleset[] = [
  {
    "id": "nomini",
    "name": "Nomini",
    "linkUrl": "https://crowsworthy.itch.io/nomini",
    "homeUrl": "#",
    "content": "The Constitution of Nomini\nVersion 0.7 | Copyright 2024 Chloe Baldwin\nReleased under CC-BY-SA 4.0 License\n\nConsider The Law you produce while playing a Nomini to be a derivative work. If you publish it anywhere, you must include the following attribution and license notice, replacing the bits in square brackets with the appropriate information:\n\n[your Nomini] is published under the CC-BY-SA 4.0 License.\n\nThis Nomini traces its development through the following Nominis:\nNomini v0.7 by Chloe Baldwin (Crowsworth): https://crowsworth.itch.io/nomini\n[a line for each other Nomini leading up to your own]\n\nIf you make a Nomini based on this one, in addition to the Nominis attributed above, add the following to your attribution:\n[your Nomini] [version/edition/date] by [your agreed-upon attribution]: [wherever the game can be accessed, acquired or inquired about]\nArticle 1. The Spirit of Nomini\nNomini is a Nomic, a type of game where you play with the rules themselves. Together you build, destroy, amend, analyze and judge the rules. You might win or lose; cooperate or compete; play fair or cheat (and maybe pay a price for it); bring the game to a peaceful end or explode it in paradoxes. Anything can happen when you play Nomini—the goal is to enjoy collaborating just to find out what happens when you do. In the words of Agora, treat Nomini and the other players right good forever.\n\nArticle 2. The Law\nAt the start of the game, the players shall ratify a charter founding their new Nomini, signing themselves on as players thereof and putting into effect this Constitution of Nomini as well as any other articles they elect to include. Thereafter all players must abide by all the rules of the game in the form in which they are currently in effect. Together, these rules and the documents that contain them constitute The Law.\n\nArticle 3. Actions\nPlayers may take any action not prohibited by The Law by publicizing their intent to act and the effects of their action, which effects are to be made actual if and only if the action succeeds.\n\nTo publicize, also publication, is to make something unambiguously known to all players in all necessary detail. An action succeeds if and only if it meets all requirements to perform that action and passes all tests for its success, as specified by The Law. If The Law specifies no requirements or tests for an action, it succeeds automatically.\n\n3. a. Legislation\nActions that change The Law must be publicized in an unambiguously finalized and permanent form and shall be put to a vote by all players, where each player may either approve or not approve the action, to succeed if an absolute majority approves.\n\n3. b. Calls for Judgment\nA Call for Judgment (CFJ) over cases of uncertainty in the interpretation of The Law, a question of the validity of an action or effect, or the perception of any thing to be in violation of The Law, shall succeed if seconded. The acting player must include in their publication a summary of the question or case at issue.\n\n3. c. Other Actions\nUnless defined elsewhere in The Law, all other actions shall be put to a vote by all players, where each player may either approve or object. The action succeeds if the number of approvals exceeds a third of the players plus one for each objection.\n\nArticle 4. Judgment\nUpon the success of a Call for Judgment, the players shall elect a judge to rule on the issue. Every player, except the player who made the CFJ and those whose actions are at issue, is an eligible candidate. Each player may object to any or all of the candidates, including themselves. The single candidate with the fewest objections shall be appointed judge. If no candidate avails, the CFJ ends with no ruling.\n\nIt is the duty of the judge to deliver a fair ruling on the issue for which they have been elected. Each player shall be afforded the opportunity to voice their position and argument on the issue for the judge to consider. Thereafter, with due deliberation, the judge shall publicize their final ruling. Said ruling is effective from the moment of its publication.\n\nRulings may freely enact any rule or effect within the bounds of the issue, but may only institute persistent changes to the game, such as overruling future judgment, ousting players, or changing The Law, by issuing them as one or more actions.\n\nArticle 5. Life and Renewal\nPlayers may leave the game freely. Players may add newcomers to the charter with an action.\n\nPlay Nomini until you have found out. Play until the game is perfect. Play until the game is utterly broken. Play for as long as you are enjoying it. Play until you want to find something else out and then start a new Nomini. If that new Nomini is based on the one you're playing right now, that's called a Renewal. The founders of a Renewal are free to copy The Law in full or in part, to edit or alter it, and to add to it rules of their own devising or from other Nominis.\n\nLet Nomini be held in common by all.\n\nCredit\nNomic is the original creation of Peter Suber.\n\nThe new Nomini gavel icon is derived from Delapouite's \"Banging gavel icon,\" and is Copyright 2025 Chloe Baldwin. All rights reserved.\n\nThe old Nomini gavel icon is derived from Lorc's \"Gavel icon,\" and is released under CC BY 4.0 International.",
    "metrics": {
      "words": 915,
      "characters": 5269,
      "uniqueWordCount": 342,
      "wordSet": [
        "the",
        "constitution",
        "of",
        "nomini",
        "version",
        "07",
        "copyright",
        "2024",
        "chloe",
        "baldwin",
        "released",
        "under",
        "ccbysa",
        "40",
        "license",
        "consider",
        "law",
        "you",
        "produce",
        "while",
        "playing",
        "a",
        "to",
        "be",
        "derivative",
        "work",
        "if",
        "publish",
        "it",
        "anywhere",
        "must",
        "include",
        "following",
        "attribution",
        "and",
        "notice",
        "replacing",
        "bits",
        "in",
        "square",
        "brackets",
        "with",
        "appropriate",
        "information",
        "your",
        "is",
        "published",
        "this",
        "traces",
        "its",
        "development",
        "through",
        "nominis",
        "v07",
        "by",
        "crowsworth",
        "httpscrowsworthitchionomini",
        "line",
        "for",
        "each",
        "other",
        "leading",
        "up",
        "own",
        "make",
        "based",
        "on",
        "one",
        "addition",
        "attributed",
        "above",
        "add",
        "versioneditiondate",
        "agreedupon",
        "wherever",
        "game",
        "can",
        "accessed",
        "acquired",
        "or",
        "inquired",
        "about",
        "article",
        "1",
        "spirit",
        "nomic",
        "type",
        "where",
        "play",
        "rules",
        "themselves",
        "together",
        "build",
        "destroy",
        "amend",
        "analyze",
        "judge",
        "might",
        "win",
        "lose",
        "cooperate",
        "compete",
        "fair",
        "cheat",
        "maybe",
        "pay",
        "price",
        "bring",
        "peaceful",
        "end",
        "explode",
        "paradoxes",
        "anything",
        "happen",
        "when",
        "nominithe",
        "goal",
        "enjoy",
        "collaborating",
        "just",
        "find",
        "out",
        "what",
        "happens",
        "do",
        "words",
        "agora",
        "treat",
        "players",
        "right",
        "good",
        "forever",
        "2",
        "at",
        "start",
        "shall",
        "ratify",
        "charter",
        "founding",
        "their",
        "new",
        "signing",
        "as",
        "thereof",
        "putting",
        "into",
        "effect",
        "well",
        "any",
        "articles",
        "they",
        "elect",
        "thereafter",
        "all",
        "abide",
        "form",
        "which",
        "are",
        "currently",
        "these",
        "documents",
        "that",
        "contain",
        "them",
        "constitute",
        "3",
        "actions",
        "may",
        "take",
        "action",
        "not",
        "prohibited",
        "publicizing",
        "intent",
        "act",
        "effects",
        "made",
        "actual",
        "only",
        "succeeds",
        "publicize",
        "also",
        "publication",
        "something",
        "unambiguously",
        "known",
        "necessary",
        "detail",
        "an",
        "meets",
        "requirements",
        "perform",
        "passes",
        "tests",
        "success",
        "specified",
        "specifies",
        "no",
        "automatically",
        "legislation",
        "change",
        "publicized",
        "finalized",
        "permanent",
        "put",
        "vote",
        "player",
        "either",
        "approve",
        "succeed",
        "absolute",
        "majority",
        "approves",
        "b",
        "calls",
        "judgment",
        "call",
        "cfj",
        "over",
        "cases",
        "uncertainty",
        "interpretation",
        "question",
        "validity",
        "perception",
        "thing",
        "violation",
        "seconded",
        "acting",
        "summary",
        "case",
        "issue",
        "c",
        "unless",
        "defined",
        "elsewhere",
        "object",
        "number",
        "approvals",
        "exceeds",
        "third",
        "plus",
        "objection",
        "4",
        "upon",
        "rule",
        "every",
        "except",
        "who",
        "those",
        "whose",
        "eligible",
        "candidate",
        "candidates",
        "including",
        "single",
        "fewest",
        "objections",
        "appointed",
        "avails",
        "ends",
        "ruling",
        "duty",
        "deliver",
        "have",
        "been",
        "elected",
        "afforded",
        "opportunity",
        "voice",
        "position",
        "argument",
        "due",
        "deliberation",
        "final",
        "said",
        "effective",
        "from",
        "moment",
        "rulings",
        "freely",
        "enact",
        "within",
        "bounds",
        "but",
        "institute",
        "persistent",
        "changes",
        "such",
        "overruling",
        "future",
        "ousting",
        "changing",
        "issuing",
        "more",
        "5",
        "life",
        "renewal",
        "leave",
        "newcomers",
        "until",
        "found",
        "perfect",
        "utterly",
        "broken",
        "long",
        "enjoying",
        "want",
        "else",
        "then",
        "youre",
        "now",
        "thats",
        "called",
        "founders",
        "free",
        "copy",
        "full",
        "part",
        "edit",
        "alter",
        "devising",
        "let",
        "held",
        "common",
        "credit",
        "original",
        "creation",
        "peter",
        "suber",
        "gavel",
        "icon",
        "derived",
        "delapouites",
        "banging",
        "2025",
        "rights",
        "reserved",
        "old",
        "lorcs",
        "cc",
        "international"
      ],
      "wordCounts": {
        "1": 1,
        "2": 1,
        "3": 4,
        "4": 1,
        "5": 1,
        "40": 3,
        "2024": 1,
        "2025": 1,
        "the": 74,
        "constitution": 2,
        "of": 25,
        "nomini": 19,
        "version": 1,
        "07": 1,
        "copyright": 2,
        "chloe": 3,
        "baldwin": 3,
        "released": 2,
        "under": 3,
        "ccbysa": 2,
        "license": 3,
        "consider": 2,
        "law": 12,
        "you": 12,
        "produce": 1,
        "while": 1,
        "playing": 2,
        "a": 22,
        "to": 30,
        "be": 10,
        "derivative": 1,
        "work": 1,
        "if": 12,
        "publish": 1,
        "it": 9,
        "anywhere": 1,
        "must": 4,
        "include": 3,
        "following": 3,
        "attribution": 3,
        "and": 19,
        "notice": 1,
        "replacing": 1,
        "bits": 1,
        "in": 16,
        "square": 1,
        "brackets": 1,
        "with": 6,
        "appropriate": 1,
        "information": 1,
        "your": 5,
        "is": 15,
        "published": 1,
        "this": 3,
        "traces": 1,
        "its": 3,
        "development": 1,
        "through": 1,
        "nominis": 3,
        "v07": 1,
        "by": 11,
        "crowsworth": 1,
        "httpscrowsworthitchionomini": 1,
        "line": 1,
        "for": 11,
        "each": 6,
        "other": 6,
        "leading": 1,
        "up": 1,
        "own": 2,
        "make": 2,
        "based": 2,
        "on": 6,
        "one": 4,
        "addition": 1,
        "attributed": 1,
        "above": 1,
        "add": 3,
        "versioneditiondate": 1,
        "agreedupon": 1,
        "wherever": 1,
        "game": 9,
        "can": 2,
        "accessed": 1,
        "acquired": 1,
        "or": 18,
        "inquired": 1,
        "about": 1,
        "article": 5,
        "spirit": 1,
        "nomic": 2,
        "type": 1,
        "where": 3,
        "play": 8,
        "rules": 5,
        "themselves": 3,
        "together": 2,
        "build": 1,
        "destroy": 1,
        "amend": 1,
        "analyze": 1,
        "judge": 6,
        "might": 1,
        "win": 1,
        "lose": 1,
        "cooperate": 1,
        "compete": 1,
        "fair": 2,
        "cheat": 1,
        "maybe": 1,
        "pay": 1,
        "price": 1,
        "bring": 1,
        "peaceful": 1,
        "end": 1,
        "explode": 1,
        "paradoxes": 1,
        "anything": 1,
        "happen": 1,
        "when": 2,
        "nominithe": 1,
        "goal": 1,
        "enjoy": 1,
        "collaborating": 1,
        "just": 1,
        "find": 2,
        "out": 3,
        "what": 1,
        "happens": 1,
        "do": 1,
        "words": 1,
        "agora": 1,
        "treat": 1,
        "players": 13,
        "right": 2,
        "good": 1,
        "forever": 1,
        "at": 3,
        "start": 2,
        "shall": 8,
        "ratify": 1,
        "charter": 2,
        "founding": 1,
        "their": 7,
        "new": 4,
        "signing": 1,
        "as": 8,
        "thereof": 1,
        "putting": 1,
        "into": 1,
        "effect": 4,
        "well": 1,
        "any": 5,
        "articles": 1,
        "they": 3,
        "elect": 2,
        "thereafter": 2,
        "all": 12,
        "abide": 1,
        "form": 2,
        "which": 3,
        "are": 5,
        "currently": 1,
        "these": 1,
        "documents": 1,
        "that": 4,
        "contain": 1,
        "them": 2,
        "constitute": 1,
        "actions": 6,
        "may": 8,
        "take": 1,
        "action": 10,
        "not": 2,
        "prohibited": 1,
        "publicizing": 1,
        "intent": 1,
        "act": 1,
        "effects": 2,
        "made": 2,
        "actual": 1,
        "only": 3,
        "succeeds": 4,
        "publicize": 2,
        "also": 1,
        "publication": 3,
        "something": 2,
        "unambiguously": 2,
        "known": 1,
        "necessary": 1,
        "detail": 1,
        "an": 7,
        "meets": 1,
        "requirements": 2,
        "perform": 1,
        "passes": 1,
        "tests": 2,
        "success": 2,
        "specified": 1,
        "specifies": 1,
        "no": 3,
        "automatically": 1,
        "legislation": 1,
        "change": 1,
        "publicized": 1,
        "finalized": 1,
        "permanent": 1,
        "put": 2,
        "vote": 2,
        "player": 7,
        "either": 2,
        "approve": 3,
        "succeed": 2,
        "absolute": 1,
        "majority": 1,
        "approves": 1,
        "b": 1,
        "calls": 1,
        "judgment": 5,
        "call": 2,
        "cfj": 3,
        "over": 1,
        "cases": 1,
        "uncertainty": 1,
        "interpretation": 1,
        "question": 2,
        "validity": 1,
        "perception": 1,
        "thing": 1,
        "violation": 1,
        "seconded": 1,
        "acting": 1,
        "summary": 1,
        "case": 1,
        "issue": 6,
        "c": 1,
        "unless": 1,
        "defined": 1,
        "elsewhere": 1,
        "object": 2,
        "number": 1,
        "approvals": 1,
        "exceeds": 1,
        "third": 1,
        "plus": 1,
        "objection": 1,
        "upon": 1,
        "rule": 2,
        "every": 1,
        "except": 1,
        "who": 1,
        "those": 1,
        "whose": 1,
        "eligible": 1,
        "candidate": 3,
        "candidates": 1,
        "including": 1,
        "single": 1,
        "fewest": 1,
        "objections": 1,
        "appointed": 1,
        "avails": 1,
        "ends": 1,
        "ruling": 4,
        "duty": 1,
        "deliver": 1,
        "have": 2,
        "been": 1,
        "elected": 1,
        "afforded": 1,
        "opportunity": 1,
        "voice": 1,
        "position": 1,
        "argument": 1,
        "due": 1,
        "deliberation": 1,
        "final": 1,
        "said": 1,
        "effective": 1,
        "from": 4,
        "moment": 1,
        "rulings": 1,
        "freely": 2,
        "enact": 1,
        "within": 1,
        "bounds": 1,
        "but": 1,
        "institute": 1,
        "persistent": 1,
        "changes": 1,
        "such": 1,
        "overruling": 1,
        "future": 1,
        "ousting": 1,
        "changing": 1,
        "issuing": 1,
        "more": 1,
        "life": 1,
        "renewal": 3,
        "leave": 1,
        "newcomers": 1,
        "until": 4,
        "found": 1,
        "perfect": 1,
        "utterly": 1,
        "broken": 1,
        "long": 1,
        "enjoying": 1,
        "want": 1,
        "else": 1,
        "then": 1,
        "youre": 1,
        "now": 1,
        "thats": 1,
        "called": 1,
        "founders": 1,
        "free": 1,
        "copy": 1,
        "full": 1,
        "part": 1,
        "edit": 1,
        "alter": 1,
        "devising": 1,
        "let": 1,
        "held": 1,
        "common": 1,
        "credit": 1,
        "original": 1,
        "creation": 1,
        "peter": 1,
        "suber": 1,
        "gavel": 4,
        "icon": 4,
        "derived": 2,
        "delapouites": 1,
        "banging": 1,
        "rights": 1,
        "reserved": 1,
        "old": 1,
        "lorcs": 1,
        "cc": 1,
        "international": 1
      }
    }
  },
  {
    "id": "original",
    "name": "Original",
    "linkUrl": "https://legacy.earlham.edu/~peters/writing/nomic.htm#initial%20set",
    "homeUrl": "#",
    "content": "Initial Set of Rules\nImmutable Rules\n101. All players must always abide by all the rules then in effect, in the form in which they are then in effect. The rules in the Initial Set are in effect whenever a game begins. The Initial Set consists of Rules 101-116 (immutable) and 201-213 (mutable).\n\n*\n102. Initially rules in the 100's are immutable and rules in the 200's are mutable. Rules subsequently enacted or transmuted (that is, changed from immutable to mutable or vice versa) may be immutable or mutable regardless of their numbers, and rules in the Initial Set may be transmuted regardless of their numbers.\n\n*\n103. A rule-change is any of the following: (1) the enactment, repeal, or amendment of a mutable rule; (2) the enactment, repeal, or amendment of an amendment of a mutable rule; or (3) the transmutation of an immutable rule into a mutable rule or vice versa.\n\n(Note: This definition implies that, at least initially, all new rules are mutable; immutable rules, as long as they are immutable, may not be amended or repealed; mutable rules, as long as they are mutable, may be amended or repealed; any rule of any status may be transmuted; no rule is absolutely immune to change.)\n\n*\n104. All rule-changes proposed in the proper way shall be voted on. They will be adopted if and only if they receive the required number of votes.\n\n*\n105. Every player is an eligible voter. Every eligible voter must participate in every vote on rule-changes.\n\n*\n106. All proposed rule-changes shall be written down before they are voted on. If they are adopted, they shall guide play in the form in which they were voted on.\n\n*\n107. No rule-change may take effect earlier than the moment of the completion of the vote that adopted it, even if its wording explicitly states otherwise. No rule-change may have retroactive application.\n\n*\n108. Each proposed rule-change shall be given a number for reference. The numbers shall begin with 301, and each rule-change proposed in the proper way shall receive the next successive integer, whether or not the proposal is adopted.\n\nIf a rule is repealed and reenacted, it receives the number of the proposal to reenact it. If a rule is amended or transmuted, it receives the number of the proposal to amend or transmute it. If an amendment is amended or repealed, the entire rule of which it is a part receives the number of the proposal to amend or repeal the amendment.\n\n*\n109. Rule-changes that transmute immutable rules into mutable rules may be adopted if and only if the vote is unanimous among the eligible voters. Transmutation shall not be implied, but must be stated explicitly in a proposal to take effect.\n\n*\n110. In a conflict between a mutable and an immutable rule, the immutable rule takes precedence and the mutable rule shall be entirely void. For the purposes of this rule a proposal to transmute an immutable rule does not \"conflict\" with that immutable rule.\n\n*\n111. If a rule-change as proposed is unclear, ambiguous, paradoxical, or destructive of play, or if it arguably consists of two or more rule-changes compounded or is an amendment that makes no difference, or if it is otherwise of questionable value, then the other players may suggest amendments or argue against the proposal before the vote. A reasonable time must be allowed for this debate. The proponent decides the final form in which the proposal is to be voted on and, unless the Judge has been asked to do so, also decides the time to end debate and vote.\n\n*\n112. The state of affairs that constitutes winning may not be altered from achieving n points to any other state of affairs. The magnitude of n and the means of earning points may be changed, and rules that establish a winner when play cannot continue may be enacted and (while they are mutable) be amended or repealed.\n\n*\n113. A player always has the option to forfeit the game rather than continue to play or incur a game penalty. No penalty worse than losing, in the judgment of the player to incur it, may be imposed.\n\n*\n114. There must always be at least one mutable rule. The adoption of rule-changes must never become completely impermissible.\n\n*\n115. Rule-changes that affect rules needed to allow or apply rule-changes are as permissible as other rule-changes. Even rule-changes that amend or repeal their own authority are permissible. No rule-change or type of move is impermissible solely on account of the self-reference or self-application of a rule.\n\n*\n116. Whatever is not prohibited or regulated by a rule is permitted and unregulated, with the sole exception of changing the rules, which is permitted only when a rule or set of rules explicitly or implicitly permits it.\n\n*\nMutable Rules\n201. Players shall alternate in clockwise order, taking one whole turn apiece. Turns may not be skipped or passed, and parts of turns may not be omitted. All players begin with zero points.\n\nIn mail and computer games, players shall alternate in alphabetical order by surname.\n\n*\n202. One turn consists of two parts in this order: (1) proposing one rule-change and having it voted on, and (2) throwing one die once and adding the number of points on its face to one's score.\n\nIn mail and computer games, instead of throwing a die, players subtract 291 from the ordinal number of their proposal and multiply the result by the fraction of favorable votes it received, rounded to the nearest integer. (This yields a number between 0 and 10 for the first player, with the upper limit increasing by one each turn; more points are awarded for more popular proposals.)\n\n*\n203. A rule-change is adopted if and only if the vote is unanimous among the eligible voters. If this rule is not amended by the end of the second complete circuit of turns, it automatically changes to require only a simple majority.\n\n*\n204. If and when rule-changes can be adopted without unanimity, the players who vote against winning proposals shall receive 10 points each.\n\n*\n205. An adopted rule-change takes full effect at the moment of the completion of the vote that adopted it.\n\n*\n206. When a proposed rule-change is defeated, the player who proposed it loses 10 points.\n\n*\n207. Each player always has exactly one vote.\n\n*\n208. The winner is the first player to achieve 100 (positive) points.\n\nIn mail and computer games, the winner is the first player to achieve 200 (positive) points.\n\n*\n209. At no time may there be more than 25 mutable rules.\n\n*\n210. Players may not conspire or consult on the making of future rule-changes unless they are team-mates.\n\nThe first paragraph of this rule does not apply to games by mail or computer.\n\n*\n211. If two or more mutable rules conflict with one another, or if two or more immutable rules conflict with one another, then the rule with the lowest ordinal number takes precedence.\n\nIf at least one of the rules in conflict explicitly says of itself that it defers to another rule (or type of rule) or takes precedence over another rule (or type of rule), then such provisions shall supersede the numerical method for determining precedence.\n\nIf two or more rules claim to take precedence over one another or to defer to one another, then the numerical method again governs.\n\n*\n212. If players disagree about the legality of a move or the interpretation or application of a rule, then the player preceding the one moving is to be the Judge and decide the question. Disagreement for the purposes of this rule may be created by the insistence of any player. This process is called invoking Judgment.\n\nWhen Judgment has been invoked, the next player may not begin his or her turn without the consent of a majority of the other players.\n\nThe Judge's Judgment may be overruled only by a unanimous vote of the other players taken before the next turn is begun. If a Judge's Judgment is overruled, then the player preceding the Judge in the playing order becomes the new Judge for the question, and so on, except that no player is to be Judge during his or her own turn or during the turn of a team-mate.\n\nUnless a Judge is overruled, one Judge settles all questions arising from the game until the next turn is begun, including questions as to his or her own legitimacy and jurisdiction as Judge.\n\nNew Judges are not bound by the decisions of old Judges. New Judges may, however, settle only those questions on which the players currently disagree and that affect the completion of the turn in which Judgment was invoked. All decisions by Judges shall be in accordance with all the rules then in effect; but when the rules are silent, inconsistent, or unclear on the point at issue, then the Judge shall consider game-custom and the spirit of the game before applying other standards.\n\n*\n213. If the rules are changed so that further play is impossible, or if the legality of a move cannot be determined with finality, or if by the Judge's best reasoning, not overruled, a move appears equally legal and illegal, then the first player unable to complete a turn is the winner.\n\nThis rule takes precedence over every other rule determining the winner.",
    "metrics": {
      "words": 1582,
      "characters": 9055,
      "uniqueWordCount": 424,
      "wordSet": [
        "initial",
        "set",
        "of",
        "rules",
        "immutable",
        "101",
        "all",
        "players",
        "must",
        "always",
        "abide",
        "by",
        "the",
        "then",
        "in",
        "effect",
        "form",
        "which",
        "they",
        "are",
        "whenever",
        "a",
        "game",
        "begins",
        "consists",
        "101116",
        "and",
        "201213",
        "mutable",
        "102",
        "initially",
        "100s",
        "200s",
        "subsequently",
        "enacted",
        "or",
        "transmuted",
        "that",
        "is",
        "changed",
        "from",
        "to",
        "vice",
        "versa",
        "may",
        "be",
        "regardless",
        "their",
        "numbers",
        "103",
        "rulechange",
        "any",
        "following",
        "1",
        "enactment",
        "repeal",
        "amendment",
        "rule",
        "2",
        "an",
        "3",
        "transmutation",
        "into",
        "note",
        "this",
        "definition",
        "implies",
        "at",
        "least",
        "new",
        "as",
        "long",
        "not",
        "amended",
        "repealed",
        "status",
        "no",
        "absolutely",
        "immune",
        "change",
        "104",
        "rulechanges",
        "proposed",
        "proper",
        "way",
        "shall",
        "voted",
        "on",
        "will",
        "adopted",
        "if",
        "only",
        "receive",
        "required",
        "number",
        "votes",
        "105",
        "every",
        "player",
        "eligible",
        "voter",
        "participate",
        "vote",
        "106",
        "written",
        "down",
        "before",
        "guide",
        "play",
        "were",
        "107",
        "take",
        "earlier",
        "than",
        "moment",
        "completion",
        "it",
        "even",
        "its",
        "wording",
        "explicitly",
        "states",
        "otherwise",
        "have",
        "retroactive",
        "application",
        "108",
        "each",
        "given",
        "for",
        "reference",
        "begin",
        "with",
        "301",
        "next",
        "successive",
        "integer",
        "whether",
        "proposal",
        "reenacted",
        "receives",
        "reenact",
        "amend",
        "transmute",
        "entire",
        "part",
        "109",
        "unanimous",
        "among",
        "voters",
        "implied",
        "but",
        "stated",
        "110",
        "conflict",
        "between",
        "takes",
        "precedence",
        "entirely",
        "void",
        "purposes",
        "does",
        "111",
        "unclear",
        "ambiguous",
        "paradoxical",
        "destructive",
        "arguably",
        "two",
        "more",
        "compounded",
        "makes",
        "difference",
        "questionable",
        "value",
        "other",
        "suggest",
        "amendments",
        "argue",
        "against",
        "reasonable",
        "time",
        "allowed",
        "debate",
        "proponent",
        "decides",
        "final",
        "unless",
        "judge",
        "has",
        "been",
        "asked",
        "do",
        "so",
        "also",
        "end",
        "112",
        "state",
        "affairs",
        "constitutes",
        "winning",
        "altered",
        "achieving",
        "n",
        "points",
        "magnitude",
        "means",
        "earning",
        "establish",
        "winner",
        "when",
        "cannot",
        "continue",
        "while",
        "113",
        "option",
        "forfeit",
        "rather",
        "incur",
        "penalty",
        "worse",
        "losing",
        "judgment",
        "imposed",
        "114",
        "there",
        "one",
        "adoption",
        "never",
        "become",
        "completely",
        "impermissible",
        "115",
        "affect",
        "needed",
        "allow",
        "apply",
        "permissible",
        "own",
        "authority",
        "type",
        "move",
        "solely",
        "account",
        "selfreference",
        "selfapplication",
        "116",
        "whatever",
        "prohibited",
        "regulated",
        "permitted",
        "unregulated",
        "sole",
        "exception",
        "changing",
        "implicitly",
        "permits",
        "201",
        "alternate",
        "clockwise",
        "order",
        "taking",
        "whole",
        "turn",
        "apiece",
        "turns",
        "skipped",
        "passed",
        "parts",
        "omitted",
        "zero",
        "mail",
        "computer",
        "games",
        "alphabetical",
        "surname",
        "202",
        "proposing",
        "having",
        "throwing",
        "die",
        "once",
        "adding",
        "face",
        "ones",
        "score",
        "instead",
        "subtract",
        "291",
        "ordinal",
        "multiply",
        "result",
        "fraction",
        "favorable",
        "received",
        "rounded",
        "nearest",
        "yields",
        "0",
        "10",
        "first",
        "upper",
        "limit",
        "increasing",
        "awarded",
        "popular",
        "proposals",
        "203",
        "second",
        "complete",
        "circuit",
        "automatically",
        "changes",
        "require",
        "simple",
        "majority",
        "204",
        "can",
        "without",
        "unanimity",
        "who",
        "205",
        "full",
        "206",
        "defeated",
        "loses",
        "207",
        "exactly",
        "208",
        "achieve",
        "100",
        "positive",
        "200",
        "209",
        "25",
        "210",
        "conspire",
        "consult",
        "making",
        "future",
        "teammates",
        "paragraph",
        "211",
        "another",
        "lowest",
        "says",
        "itself",
        "defers",
        "over",
        "such",
        "provisions",
        "supersede",
        "numerical",
        "method",
        "determining",
        "claim",
        "defer",
        "again",
        "governs",
        "212",
        "disagree",
        "about",
        "legality",
        "interpretation",
        "preceding",
        "moving",
        "decide",
        "question",
        "disagreement",
        "created",
        "insistence",
        "process",
        "called",
        "invoking",
        "invoked",
        "his",
        "her",
        "consent",
        "judges",
        "overruled",
        "taken",
        "begun",
        "playing",
        "becomes",
        "except",
        "during",
        "teammate",
        "settles",
        "questions",
        "arising",
        "until",
        "including",
        "legitimacy",
        "jurisdiction",
        "bound",
        "decisions",
        "old",
        "however",
        "settle",
        "those",
        "currently",
        "was",
        "accordance",
        "silent",
        "inconsistent",
        "point",
        "issue",
        "consider",
        "gamecustom",
        "spirit",
        "applying",
        "standards",
        "213",
        "further",
        "impossible",
        "determined",
        "finality",
        "best",
        "reasoning",
        "appears",
        "equally",
        "legal",
        "illegal",
        "unable"
      ],
      "wordCounts": {
        "0": 1,
        "1": 2,
        "2": 2,
        "3": 1,
        "10": 3,
        "25": 1,
        "100": 1,
        "101": 1,
        "102": 1,
        "103": 1,
        "104": 1,
        "105": 1,
        "106": 1,
        "107": 1,
        "108": 1,
        "109": 1,
        "110": 1,
        "111": 1,
        "112": 1,
        "113": 1,
        "114": 1,
        "115": 1,
        "116": 1,
        "200": 1,
        "201": 1,
        "202": 1,
        "203": 1,
        "204": 1,
        "205": 1,
        "206": 1,
        "207": 1,
        "208": 1,
        "209": 1,
        "210": 1,
        "211": 1,
        "212": 1,
        "213": 1,
        "291": 1,
        "301": 1,
        "101116": 1,
        "201213": 1,
        "initial": 4,
        "set": 5,
        "of": 60,
        "rules": 27,
        "immutable": 14,
        "all": 9,
        "players": 12,
        "must": 6,
        "always": 4,
        "abide": 1,
        "by": 12,
        "the": 119,
        "then": 11,
        "in": 29,
        "effect": 7,
        "form": 3,
        "which": 7,
        "they": 11,
        "are": 17,
        "whenever": 1,
        "a": 36,
        "game": 5,
        "begins": 1,
        "consists": 3,
        "and": 32,
        "mutable": 18,
        "initially": 2,
        "100s": 1,
        "200s": 1,
        "subsequently": 1,
        "enacted": 2,
        "or": 49,
        "transmuted": 4,
        "that": 15,
        "is": 33,
        "changed": 3,
        "from": 4,
        "to": 29,
        "vice": 2,
        "versa": 2,
        "may": 21,
        "be": 31,
        "regardless": 2,
        "their": 4,
        "numbers": 3,
        "rulechange": 11,
        "any": 5,
        "following": 1,
        "enactment": 2,
        "repeal": 4,
        "amendment": 6,
        "rule": 30,
        "an": 8,
        "transmutation": 2,
        "into": 2,
        "note": 1,
        "this": 10,
        "definition": 1,
        "implies": 1,
        "at": 6,
        "least": 3,
        "new": 4,
        "as": 9,
        "long": 2,
        "not": 14,
        "amended": 6,
        "repealed": 5,
        "status": 1,
        "no": 8,
        "absolutely": 1,
        "immune": 1,
        "change": 1,
        "rulechanges": 12,
        "proposed": 7,
        "proper": 2,
        "way": 2,
        "shall": 14,
        "voted": 5,
        "on": 12,
        "will": 1,
        "adopted": 9,
        "if": 25,
        "only": 7,
        "receive": 3,
        "required": 1,
        "number": 9,
        "votes": 2,
        "every": 4,
        "player": 14,
        "eligible": 4,
        "voter": 2,
        "participate": 1,
        "vote": 10,
        "written": 1,
        "down": 1,
        "before": 4,
        "guide": 1,
        "play": 5,
        "were": 1,
        "take": 3,
        "earlier": 1,
        "than": 4,
        "moment": 2,
        "completion": 3,
        "it": 16,
        "even": 2,
        "its": 2,
        "wording": 1,
        "explicitly": 4,
        "states": 1,
        "otherwise": 2,
        "have": 1,
        "retroactive": 1,
        "application": 2,
        "each": 5,
        "given": 1,
        "for": 8,
        "reference": 1,
        "begin": 3,
        "with": 10,
        "next": 4,
        "successive": 1,
        "integer": 2,
        "whether": 1,
        "proposal": 9,
        "reenacted": 1,
        "receives": 3,
        "reenact": 1,
        "amend": 3,
        "transmute": 3,
        "entire": 1,
        "part": 1,
        "unanimous": 3,
        "among": 2,
        "voters": 2,
        "implied": 1,
        "but": 2,
        "stated": 1,
        "conflict": 5,
        "between": 2,
        "takes": 5,
        "precedence": 6,
        "entirely": 1,
        "void": 1,
        "purposes": 2,
        "does": 2,
        "unclear": 2,
        "ambiguous": 1,
        "paradoxical": 1,
        "destructive": 1,
        "arguably": 1,
        "two": 5,
        "more": 7,
        "compounded": 1,
        "makes": 1,
        "difference": 1,
        "questionable": 1,
        "value": 1,
        "other": 7,
        "suggest": 1,
        "amendments": 1,
        "argue": 1,
        "against": 2,
        "reasonable": 1,
        "time": 3,
        "allowed": 1,
        "debate": 2,
        "proponent": 1,
        "decides": 2,
        "final": 1,
        "unless": 3,
        "judge": 9,
        "has": 4,
        "been": 2,
        "asked": 1,
        "do": 1,
        "so": 3,
        "also": 1,
        "end": 2,
        "state": 2,
        "affairs": 2,
        "constitutes": 1,
        "winning": 2,
        "altered": 1,
        "achieving": 1,
        "n": 2,
        "points": 9,
        "magnitude": 1,
        "means": 1,
        "earning": 1,
        "establish": 1,
        "winner": 5,
        "when": 6,
        "cannot": 2,
        "continue": 2,
        "while": 1,
        "option": 1,
        "forfeit": 1,
        "rather": 1,
        "incur": 2,
        "penalty": 2,
        "worse": 1,
        "losing": 1,
        "judgment": 6,
        "imposed": 1,
        "there": 2,
        "one": 14,
        "adoption": 1,
        "never": 1,
        "become": 1,
        "completely": 1,
        "impermissible": 2,
        "affect": 2,
        "needed": 1,
        "allow": 1,
        "apply": 2,
        "permissible": 2,
        "own": 3,
        "authority": 1,
        "type": 3,
        "move": 4,
        "solely": 1,
        "account": 1,
        "selfreference": 1,
        "selfapplication": 1,
        "whatever": 1,
        "prohibited": 1,
        "regulated": 1,
        "permitted": 2,
        "unregulated": 1,
        "sole": 1,
        "exception": 1,
        "changing": 1,
        "implicitly": 1,
        "permits": 1,
        "alternate": 2,
        "clockwise": 1,
        "order": 4,
        "taking": 1,
        "whole": 1,
        "turn": 10,
        "apiece": 1,
        "turns": 3,
        "skipped": 1,
        "passed": 1,
        "parts": 2,
        "omitted": 1,
        "zero": 1,
        "mail": 4,
        "computer": 4,
        "games": 4,
        "alphabetical": 1,
        "surname": 1,
        "proposing": 1,
        "having": 1,
        "throwing": 2,
        "die": 2,
        "once": 1,
        "adding": 1,
        "face": 1,
        "ones": 1,
        "score": 1,
        "instead": 1,
        "subtract": 1,
        "ordinal": 2,
        "multiply": 1,
        "result": 1,
        "fraction": 1,
        "favorable": 1,
        "received": 1,
        "rounded": 1,
        "nearest": 1,
        "yields": 1,
        "first": 5,
        "upper": 1,
        "limit": 1,
        "increasing": 1,
        "awarded": 1,
        "popular": 1,
        "proposals": 2,
        "second": 1,
        "complete": 2,
        "circuit": 1,
        "automatically": 1,
        "changes": 1,
        "require": 1,
        "simple": 1,
        "majority": 2,
        "can": 1,
        "without": 2,
        "unanimity": 1,
        "who": 2,
        "full": 1,
        "defeated": 1,
        "loses": 1,
        "exactly": 1,
        "achieve": 2,
        "positive": 2,
        "conspire": 1,
        "consult": 1,
        "making": 1,
        "future": 1,
        "teammates": 1,
        "paragraph": 1,
        "another": 6,
        "lowest": 1,
        "says": 1,
        "itself": 1,
        "defers": 1,
        "over": 3,
        "such": 1,
        "provisions": 1,
        "supersede": 1,
        "numerical": 2,
        "method": 2,
        "determining": 2,
        "claim": 1,
        "defer": 1,
        "again": 1,
        "governs": 1,
        "disagree": 2,
        "about": 1,
        "legality": 2,
        "interpretation": 1,
        "preceding": 2,
        "moving": 1,
        "decide": 1,
        "question": 2,
        "disagreement": 1,
        "created": 1,
        "insistence": 1,
        "process": 1,
        "called": 1,
        "invoking": 1,
        "invoked": 2,
        "his": 3,
        "her": 3,
        "consent": 1,
        "judges": 7,
        "overruled": 4,
        "taken": 1,
        "begun": 2,
        "playing": 1,
        "becomes": 1,
        "except": 1,
        "during": 2,
        "teammate": 1,
        "settles": 1,
        "questions": 3,
        "arising": 1,
        "until": 1,
        "including": 1,
        "legitimacy": 1,
        "jurisdiction": 1,
        "bound": 1,
        "decisions": 2,
        "old": 1,
        "however": 1,
        "settle": 1,
        "those": 1,
        "currently": 1,
        "was": 1,
        "accordance": 1,
        "silent": 1,
        "inconsistent": 1,
        "point": 1,
        "issue": 1,
        "consider": 1,
        "gamecustom": 1,
        "spirit": 1,
        "applying": 1,
        "standards": 1,
        "further": 1,
        "impossible": 1,
        "determined": 1,
        "finality": 1,
        "best": 1,
        "reasoning": 1,
        "appears": 1,
        "equally": 1,
        "legal": 1,
        "illegal": 1,
        "unable": 1
      }
    }
  },
  {
    "id": "purenomic",
    "name": "Pure Nomic",
    "linkUrl": "https://brightestbulb.net/games/pure_nomic/",
    "homeUrl": "#",
    "content": "All players must agree to any changes to the game",
    "metrics": {
      "words": 10,
      "characters": 49,
      "uniqueWordCount": 9,
      "wordSet": [
        "all",
        "players",
        "must",
        "agree",
        "to",
        "any",
        "changes",
        "the",
        "game"
      ],
      "wordCounts": {
        "all": 1,
        "players": 1,
        "must": 1,
        "agree": 1,
        "to": 2,
        "any": 1,
        "changes": 1,
        "the": 1,
        "game": 1
      }
    }
  },
  {
    "id": "trunglenomic",
    "name": "Trungle Nomic",
    "linkUrl": "https://infinite.nomic.space/wiki/index.php?title=User:Trungle/Boilerplate_Nomic",
    "homeUrl": "#",
    "content": "Trungle/Boilerplate Nomic\nThis page includes what I (Trungle) perceive to be the most standard starting ruleset using all of our preferred ways of doing things.\\nWhen creating your starting ruleset, feel free to remove any bits that aren't necessary.\\nText in italics is explanatory only and should not be included in your ruleset.\\n\\n\\n== Time ==\\n\\n\\n=== General ===\\nAll times mentioned in this ruleset are in UTC. Days start at 00:00 UTC. Weeks start on Monday 00:00 UTC.\\n\\n\\n=== Phases ===\\nEach week is divided into two phases:\\n\\nPhase I: Monday, Tuesday and Wednesday\\nPhase II: Thursday, Friday, Saturday, and Sunday\\nThe Phase Number is the number of phases since the beginning of the cycle, starting with 0 on the phase the cycle began.\\nNote 1: The phase cycle can start on Sunday or Monday depending on personal preference.\\nNote 2: Certain actions can often only be taken in one of the two phases. If this is the case, feel free to give your phases unique names.\\n\\n\\n== Rules ==\\nA rule is a body of text which governs the state of the game. Rules that are in effect apply continuously. When a player joins the game, they agree to abide by the rules in effect.\\nA subrule is a rule that claims another rule as its parent. The subrule is not part of the parent; instead this relationship is to be used for organizational purposes.\\nA rule that is not a subrule is a top-level rule.\\n\\n\\n== Players ==\\nAny person may become a player by posting a message setting forth their intent to do so in the channel ⁠#game-actions, provided they have not been a player at any point in the past seven days. A player may cease being a player by sending a message that sets forth their intent to do so in #⁠game-actions.\\nA player is reputable if they have continuously been a player for the previous seven days or if they have continuously been a player from a time that was within 3 days of the round starting.\\nNote: Reputability mechanics should not be changed without good reason.\\n\\n\\n== Proposals ==\\nProposals are made by sending a message in the channel #proposals indicating clear intent to submit a proposal.\\nA 👍 or 👎 reaction from a player on a message containing a proposal at the time when the voting period ends constitutes a vote in favor or against, respectively. If a person's vote is unclear (excluding abstentions), it is considered to be against.\\nAt the end of its voting period, a proposal takes effect if it is popular (as defined for its type) and the message in which it was submitted has been neither deleted nor edited. If more than one proposal would otherwise take effect simultaneously, they take effect in the order in which they were created.\\nThe class of a proposal must be one of the classes listed below. When a proposal is submitted, the submitter may specify its class. if no class is specified, the proposal class defaults to Standard.\\n\\n\\n=== Urgent Class Proposal ===\\nThe voting period of an urgent proposal begins at the time it is submitted and ends two days after. An urgent proposal is popular if it has no more than two votes against it.\\nRules to the contrary notwithstanding, only a reputable player can submit an urgent proposal. Urgent proposals should only be used to correct the game to its intended state and to maintain playability.\\nNote: Even if your ruleset does something interesting with the timing of actions, it is highly advised to keep Urgent-class proposals on a real time cycle. This is not a good place to inject flavor.\\n\\n\\n=== Standard Class Proposal ===\\nThe voting period for a standard proposal is the phase that started after the proposal was submitted. A standard proposal is popular if it has more votes in favor than votes against.\\nNote: This does mean that proposals' voting periods do not start immediately after the proposal is submitted. This doesn't matter with a phase system since votes are only evaluated at the end of its voting period, but if you want to have something happen \\\"during\\\" a proposal's voting period, this is something to know.\\n\\n\\n== Judgement ==\\nThere shall be a sole Judge, responsible for resolving rules disputes. An incumbent Judge can be removed with the assent of two players, but they should not be removed in this manner except for abuse of office. A person can cease being the Judge by publicly stating so.\\nA request for justice shall take the form of a question or statement. The proper response to a question is an answer to that question, and the proper response to a statement is the truth value of that statement.\\nUpon formal submission of a request for justice by a person other than themself in #request-for-justice, the Judge can and shall, as quickly as possible, issue a response to the request in ⁠#request-for-justice. This response shall be binding only to the extent that it reasonably directly pertains to the request, and only to the extent that it does not blatantly and obviously contradict rules text while still considering the expressed or clearly implied legislative intent.\\nWithin 4 days of a judge issuing a ruling, a public vote of confidence on that ruling can be initiated in #request-for-justice. Votes may be cast in such a vote for a period of 2 days after initiation. Votes are to be cast by 👍 or 👎 reactions on a clearly designated poll message; if a person's vote is unclear, it is to affirm the judgement. A ruling is overturned if strictly more players vote in favor of overturning than affirming.\\nA ruling may be overturned by the Judge who made it within one week of being made. When a ruling is overturned in this manner, the Judge shall then issue a new ruling on the initial request, which shall be binding in the same manner as the original ruling.\\nAn overturned ruling shall have no bearing on the interpretation of the rules or of the gamestate.\\nAny reputable player may become a candidate for the Judge by saying so in the channel #judge-elections. If there are any Judge candidacies put forward during a week, the player whose message is both popular and has the most 👍 reactions from players becomes the Judge once that week ends. A Judge Candidacy message is popular if it has more 👍 than 👎 reactions from players on its initiating message. Ties are broken in favor of the player with the earliest text message during that week.\\nIf no judge candidacies are put forward during a week, then the incumbent judge retains their position.\\n\\n\\n== Actions ==\\nActions that are to be performed \\\"by saying so\\\" are done by sending a message in the appropriate channel that clearly and unambiguously sets forth intent for the action to be taken.\\nWhen defining a game action that can be performed by sending a message, the rules should specify a channel where the game action can be taken. If they do not, then the action can be taken by sending the message in #game-actions indicating intention to take that action. If the rules provide that players can perform a game action without making any provision for any method to take that action, then the action can be taken by sending a message in #game-actions indicating intention to take that action. If #game-actions does not exist, then the message can be sent in #nomic disclaiming that it is intended to be a game action. \\nWhenever a player performs an action that would modify the information that the players generally agree should be tracked, that player should make a reasonable effort to track the outcome of the action in any generally-agreed-upon applicable locations or else delegate tracking to another player. When a player believes they have fulfilled this standard, they should react to the message with ✅ to indicate this.\\n\\n\\n== Randomness ==\\nWhen randomisation is concerned in this ruleset, it must be resolved by a generally trusted and fair method accessible to all players in the game, and as soon as possible.\\nWhen a rule would have a player determine something by random chance, that player should resolve the random chance as their next act, and must resolve it before other actions involving the result of the triggering event may take place - or by phase end. If the randomisation is not resolved, then, if possible, the event takes place with only the non-random, non-optional elements resolved; otherwise it does not take place.\\nFor instance, if a player receives an item with an optional random chance of special trait, they must randomly determine that trait before they may perform actions involving that item, or else the trait is not applied. If a player would receive an item with a random attribute that must be determined, they do not receive that item until the attribute is determined.\\n\\n\\n=== Random Choices ===\\nA person shall not deliberately select random values for a rules-defined action without intending to use those values to the best of their ability to resolve that action.\\nIf a person has selected some or all of the random values necessary to perform an action, they shall not discard the valid specifications in order to attempt a substantially similar action with the goal of obtaining different random values. If there is consensus that a preponderance of the evidence exists, or if a Judge ruling, not overturned, finds that a player has done such a thing, all attempts other than the first are deemed to be invalid and to not have affected the gamestate.\\n\\n\\n=== Dice Rolls ===\\nA rule that requires a selection of an NdK value, for non-negative integer N and positive integer K, requires the random selection of N rolls of a K-sided die.\\n\\nIf not otherwise specified, this produces the sum of N rolls of a K-sided die; that is, the sum of N independent selections of integers from 1 to K, using a uniform random distribution. If N is zero, the sum is zero.\\nIf a rule requires an NdK dice roll with a target number x, this instead produces the number of N independent 1dK rolls that meet or exceed the target number and can be abbreviated as \\\"x+\\\". For example, if a rule requires a dice roll with a target number of 3, this can be abbreviated to \\\"3+\\\".\\n\\n\\n== Items ==\\nItems are entities defined as such by the rules. Items can be owned by players and are stored in their inventory. When an item's owner cannot reasonably be determined using publicly available information, or if it would be owned by a non-player, it is instead destroyed.\\nItems with similar properties may be grouped together into item classes.\\nFor an entity to gain an item is for that item to be created in that entity's possession. To grant an entity an item is to create it in that entity's possession. For an entity to lose an item is for that item to be destroyed from that entity's possession. To revoke an item from an entity is to destroy it from that entity's possession.\\nReputable players may trade items from their inventories with other reputable players with the consent of all trading parties.\\nNote: While not strictly necessary, items have proven to be a very useful abstraction for most nomics.",
    "metrics": {
      "words": 1848,
      "characters": 10977,
      "uniqueWordCount": 553,
      "wordSet": [
        "trungleboilerplate",
        "nomic",
        "this",
        "page",
        "includes",
        "what",
        "i",
        "trungle",
        "perceive",
        "to",
        "be",
        "the",
        "most",
        "standard",
        "starting",
        "ruleset",
        "using",
        "all",
        "of",
        "our",
        "preferred",
        "ways",
        "doing",
        "thingsnwhen",
        "creating",
        "your",
        "feel",
        "free",
        "remove",
        "any",
        "bits",
        "that",
        "arent",
        "necessaryntext",
        "in",
        "italics",
        "is",
        "explanatory",
        "only",
        "and",
        "should",
        "not",
        "included",
        "rulesetnnn",
        "time",
        "nnn",
        "general",
        "nall",
        "times",
        "mentioned",
        "are",
        "utc",
        "days",
        "start",
        "at",
        "0000",
        "weeks",
        "on",
        "monday",
        "utcnnn",
        "phases",
        "neach",
        "week",
        "divided",
        "into",
        "two",
        "phasesnnphase",
        "tuesday",
        "wednesdaynphase",
        "ii",
        "thursday",
        "friday",
        "saturday",
        "sundaynthe",
        "phase",
        "number",
        "since",
        "beginning",
        "cycle",
        "with",
        "0",
        "begannnote",
        "1",
        "can",
        "sunday",
        "or",
        "depending",
        "personal",
        "preferencennote",
        "2",
        "certain",
        "actions",
        "often",
        "taken",
        "one",
        "if",
        "case",
        "give",
        "unique",
        "namesnnn",
        "rules",
        "na",
        "rule",
        "a",
        "body",
        "text",
        "which",
        "governs",
        "state",
        "game",
        "effect",
        "apply",
        "continuously",
        "when",
        "player",
        "joins",
        "they",
        "agree",
        "abide",
        "by",
        "effectna",
        "subrule",
        "claims",
        "another",
        "as",
        "its",
        "parent",
        "part",
        "instead",
        "relationship",
        "used",
        "for",
        "organizational",
        "purposesna",
        "toplevel",
        "rulennn",
        "players",
        "nany",
        "person",
        "may",
        "become",
        "posting",
        "message",
        "setting",
        "forth",
        "their",
        "intent",
        "do",
        "so",
        "channel",
        "gameactions",
        "provided",
        "have",
        "been",
        "point",
        "past",
        "seven",
        "cease",
        "being",
        "sending",
        "sets",
        "gameactionsna",
        "reputable",
        "previous",
        "from",
        "was",
        "within",
        "3",
        "round",
        "startingnnote",
        "reputability",
        "mechanics",
        "changed",
        "without",
        "good",
        "reasonnnn",
        "proposals",
        "nproposals",
        "made",
        "indicating",
        "clear",
        "submit",
        "proposalna",
        "reaction",
        "containing",
        "proposal",
        "voting",
        "period",
        "ends",
        "constitutes",
        "vote",
        "favor",
        "against",
        "respectively",
        "persons",
        "unclear",
        "excluding",
        "abstentions",
        "it",
        "considered",
        "againstnat",
        "end",
        "takes",
        "popular",
        "defined",
        "type",
        "submitted",
        "has",
        "neither",
        "deleted",
        "nor",
        "edited",
        "more",
        "than",
        "would",
        "otherwise",
        "take",
        "simultaneously",
        "order",
        "were",
        "creatednthe",
        "class",
        "must",
        "classes",
        "listed",
        "below",
        "submitter",
        "specify",
        "no",
        "specified",
        "defaults",
        "standardnnn",
        "urgent",
        "nthe",
        "an",
        "begins",
        "after",
        "votes",
        "itnrules",
        "contrary",
        "notwithstanding",
        "correct",
        "intended",
        "maintain",
        "playabilitynnote",
        "even",
        "does",
        "something",
        "interesting",
        "timing",
        "highly",
        "advised",
        "keep",
        "urgentclass",
        "real",
        "place",
        "inject",
        "flavornnn",
        "started",
        "againstnnote",
        "mean",
        "periods",
        "immediately",
        "doesnt",
        "matter",
        "system",
        "evaluated",
        "but",
        "you",
        "want",
        "happen",
        "during",
        "knownnn",
        "judgement",
        "nthere",
        "shall",
        "sole",
        "judge",
        "responsible",
        "resolving",
        "disputes",
        "incumbent",
        "removed",
        "assent",
        "manner",
        "except",
        "abuse",
        "office",
        "publicly",
        "stating",
        "sona",
        "request",
        "justice",
        "form",
        "question",
        "statement",
        "proper",
        "response",
        "answer",
        "truth",
        "value",
        "statementnupon",
        "formal",
        "submission",
        "other",
        "themself",
        "requestforjustice",
        "quickly",
        "possible",
        "issue",
        "binding",
        "extent",
        "reasonably",
        "directly",
        "pertains",
        "blatantly",
        "obviously",
        "contradict",
        "while",
        "still",
        "considering",
        "expressed",
        "clearly",
        "implied",
        "legislative",
        "intentnwithin",
        "4",
        "issuing",
        "ruling",
        "public",
        "confidence",
        "initiated",
        "cast",
        "such",
        "initiation",
        "reactions",
        "designated",
        "poll",
        "affirm",
        "overturned",
        "strictly",
        "overturning",
        "affirmingna",
        "who",
        "then",
        "new",
        "initial",
        "same",
        "original",
        "rulingnan",
        "bearing",
        "interpretation",
        "gamestatenany",
        "candidate",
        "saying",
        "judgeelections",
        "there",
        "candidacies",
        "put",
        "forward",
        "whose",
        "both",
        "becomes",
        "once",
        "candidacy",
        "initiating",
        "ties",
        "broken",
        "earliest",
        "weeknif",
        "retains",
        "positionnnn",
        "nactions",
        "performed",
        "done",
        "appropriate",
        "unambiguously",
        "action",
        "takennwhen",
        "defining",
        "where",
        "intention",
        "provide",
        "perform",
        "making",
        "provision",
        "method",
        "exist",
        "sent",
        "disclaiming",
        "nwhenever",
        "performs",
        "modify",
        "information",
        "generally",
        "tracked",
        "make",
        "reasonable",
        "effort",
        "track",
        "outcome",
        "generallyagreedupon",
        "applicable",
        "locations",
        "else",
        "delegate",
        "tracking",
        "believes",
        "fulfilled",
        "react",
        "indicate",
        "thisnnn",
        "randomness",
        "nwhen",
        "randomisation",
        "concerned",
        "resolved",
        "trusted",
        "fair",
        "accessible",
        "soon",
        "possiblenwhen",
        "determine",
        "random",
        "chance",
        "resolve",
        "next",
        "act",
        "before",
        "involving",
        "result",
        "triggering",
        "event",
        "nonrandom",
        "nonoptional",
        "elements",
        "placenfor",
        "instance",
        "receives",
        "item",
        "optional",
        "special",
        "trait",
        "randomly",
        "applied",
        "receive",
        "attribute",
        "determined",
        "until",
        "determinednnn",
        "choices",
        "deliberately",
        "select",
        "values",
        "rulesdefined",
        "intending",
        "use",
        "those",
        "best",
        "ability",
        "actionnif",
        "selected",
        "some",
        "necessary",
        "discard",
        "valid",
        "specifications",
        "attempt",
        "substantially",
        "similar",
        "goal",
        "obtaining",
        "different",
        "consensus",
        "preponderance",
        "evidence",
        "exists",
        "finds",
        "thing",
        "attempts",
        "first",
        "deemed",
        "invalid",
        "affected",
        "gamestatennn",
        "dice",
        "rolls",
        "requires",
        "selection",
        "ndk",
        "nonnegative",
        "integer",
        "n",
        "positive",
        "k",
        "ksided",
        "diennif",
        "produces",
        "sum",
        "die",
        "independent",
        "selections",
        "integers",
        "uniform",
        "distribution",
        "zero",
        "zeronif",
        "roll",
        "target",
        "x",
        "1dk",
        "meet",
        "exceed",
        "abbreviated",
        "example",
        "3nnn",
        "items",
        "nitems",
        "entities",
        "owned",
        "stored",
        "inventory",
        "owner",
        "cannot",
        "available",
        "nonplayer",
        "destroyednitems",
        "properties",
        "grouped",
        "together",
        "classesnfor",
        "entity",
        "gain",
        "created",
        "entitys",
        "possession",
        "grant",
        "create",
        "lose",
        "destroyed",
        "revoke",
        "destroy",
        "possessionnreputable",
        "trade",
        "inventories",
        "consent",
        "trading",
        "partiesnnote",
        "proven",
        "very",
        "useful",
        "abstraction",
        "nomics"
      ],
      "wordCounts": {
        "0": 1,
        "1": 2,
        "2": 2,
        "3": 2,
        "4": 1,
        "trungleboilerplate": 1,
        "nomic": 2,
        "this": 16,
        "page": 1,
        "includes": 1,
        "what": 1,
        "i": 2,
        "trungle": 1,
        "perceive": 1,
        "to": 56,
        "be": 38,
        "the": 103,
        "most": 3,
        "standard": 5,
        "starting": 3,
        "ruleset": 5,
        "using": 3,
        "all": 5,
        "of": 45,
        "our": 1,
        "preferred": 1,
        "ways": 1,
        "doing": 1,
        "thingsnwhen": 1,
        "creating": 1,
        "your": 4,
        "feel": 2,
        "free": 2,
        "remove": 1,
        "any": 6,
        "bits": 1,
        "that": 43,
        "arent": 1,
        "necessaryntext": 1,
        "in": 37,
        "italics": 1,
        "is": 46,
        "explanatory": 1,
        "only": 8,
        "and": 19,
        "should": 9,
        "not": 21,
        "included": 1,
        "rulesetnnn": 1,
        "time": 5,
        "nnn": 1,
        "general": 1,
        "nall": 1,
        "times": 1,
        "mentioned": 1,
        "are": 13,
        "utc": 2,
        "days": 7,
        "start": 4,
        "at": 5,
        "0000": 2,
        "weeks": 1,
        "on": 11,
        "monday": 3,
        "utcnnn": 1,
        "phases": 4,
        "neach": 1,
        "week": 5,
        "divided": 1,
        "into": 2,
        "two": 5,
        "phasesnnphase": 1,
        "tuesday": 1,
        "wednesdaynphase": 1,
        "ii": 1,
        "thursday": 1,
        "friday": 1,
        "saturday": 1,
        "sundaynthe": 1,
        "phase": 6,
        "number": 6,
        "since": 2,
        "beginning": 1,
        "cycle": 4,
        "with": 15,
        "begannnote": 1,
        "can": 16,
        "sunday": 1,
        "or": 15,
        "depending": 1,
        "personal": 1,
        "preferencennote": 1,
        "certain": 1,
        "actions": 5,
        "often": 1,
        "taken": 4,
        "one": 4,
        "if": 27,
        "case": 1,
        "give": 1,
        "unique": 1,
        "namesnnn": 1,
        "rules": 9,
        "na": 3,
        "rule": 8,
        "a": 87,
        "body": 1,
        "text": 3,
        "which": 4,
        "governs": 1,
        "state": 2,
        "game": 8,
        "effect": 4,
        "apply": 1,
        "continuously": 3,
        "when": 6,
        "player": 22,
        "joins": 1,
        "they": 14,
        "agree": 2,
        "abide": 1,
        "by": 20,
        "effectna": 1,
        "subrule": 3,
        "claims": 1,
        "another": 2,
        "as": 10,
        "its": 7,
        "parent": 2,
        "part": 1,
        "instead": 3,
        "relationship": 1,
        "used": 2,
        "for": 19,
        "organizational": 1,
        "purposesna": 1,
        "toplevel": 1,
        "rulennn": 1,
        "players": 11,
        "nany": 1,
        "person": 5,
        "may": 10,
        "become": 2,
        "posting": 1,
        "message": 16,
        "setting": 1,
        "forth": 3,
        "their": 7,
        "intent": 4,
        "do": 5,
        "so": 4,
        "channel": 5,
        "gameactions": 4,
        "provided": 1,
        "have": 9,
        "been": 4,
        "point": 1,
        "past": 1,
        "seven": 2,
        "cease": 2,
        "being": 3,
        "sending": 6,
        "sets": 2,
        "gameactionsna": 1,
        "reputable": 4,
        "previous": 1,
        "from": 9,
        "was": 3,
        "within": 2,
        "round": 1,
        "startingnnote": 1,
        "reputability": 1,
        "mechanics": 1,
        "changed": 1,
        "without": 3,
        "good": 2,
        "reasonnnn": 1,
        "proposals": 6,
        "nproposals": 1,
        "made": 3,
        "indicating": 3,
        "clear": 1,
        "submit": 2,
        "proposalna": 1,
        "reaction": 1,
        "containing": 1,
        "proposal": 15,
        "voting": 7,
        "period": 7,
        "ends": 3,
        "constitutes": 1,
        "vote": 6,
        "favor": 4,
        "against": 2,
        "respectively": 1,
        "persons": 2,
        "unclear": 2,
        "excluding": 1,
        "abstentions": 1,
        "it": 20,
        "considered": 1,
        "againstnat": 1,
        "end": 3,
        "takes": 2,
        "popular": 5,
        "defined": 2,
        "type": 1,
        "submitted": 5,
        "has": 7,
        "neither": 1,
        "deleted": 1,
        "nor": 1,
        "edited": 1,
        "more": 5,
        "than": 7,
        "would": 5,
        "otherwise": 3,
        "take": 8,
        "simultaneously": 1,
        "order": 2,
        "were": 1,
        "creatednthe": 1,
        "class": 6,
        "must": 5,
        "classes": 1,
        "listed": 1,
        "below": 1,
        "submitter": 1,
        "specify": 2,
        "no": 4,
        "specified": 2,
        "defaults": 1,
        "standardnnn": 1,
        "urgent": 5,
        "nthe": 2,
        "an": 21,
        "begins": 1,
        "after": 4,
        "votes": 6,
        "itnrules": 1,
        "contrary": 1,
        "notwithstanding": 1,
        "correct": 1,
        "intended": 2,
        "maintain": 1,
        "playabilitynnote": 1,
        "even": 1,
        "does": 5,
        "something": 4,
        "interesting": 1,
        "timing": 1,
        "highly": 1,
        "advised": 1,
        "keep": 1,
        "urgentclass": 1,
        "real": 1,
        "place": 3,
        "inject": 1,
        "flavornnn": 1,
        "started": 1,
        "againstnnote": 1,
        "mean": 1,
        "periods": 1,
        "immediately": 1,
        "doesnt": 1,
        "matter": 1,
        "system": 1,
        "evaluated": 1,
        "but": 2,
        "you": 1,
        "want": 1,
        "happen": 1,
        "during": 4,
        "knownnn": 1,
        "judgement": 2,
        "nthere": 1,
        "shall": 9,
        "sole": 1,
        "judge": 14,
        "responsible": 1,
        "resolving": 1,
        "disputes": 1,
        "incumbent": 2,
        "removed": 2,
        "assent": 1,
        "manner": 3,
        "except": 1,
        "abuse": 1,
        "office": 1,
        "publicly": 2,
        "stating": 1,
        "sona": 1,
        "request": 5,
        "justice": 2,
        "form": 1,
        "question": 3,
        "statement": 2,
        "proper": 2,
        "response": 4,
        "answer": 1,
        "truth": 1,
        "value": 2,
        "statementnupon": 1,
        "formal": 1,
        "submission": 1,
        "other": 4,
        "themself": 1,
        "requestforjustice": 3,
        "quickly": 1,
        "possible": 2,
        "issue": 2,
        "binding": 2,
        "extent": 2,
        "reasonably": 2,
        "directly": 1,
        "pertains": 1,
        "blatantly": 1,
        "obviously": 1,
        "contradict": 1,
        "while": 2,
        "still": 1,
        "considering": 1,
        "expressed": 1,
        "clearly": 3,
        "implied": 1,
        "legislative": 1,
        "intentnwithin": 1,
        "issuing": 1,
        "ruling": 8,
        "public": 1,
        "confidence": 1,
        "initiated": 1,
        "cast": 2,
        "such": 3,
        "initiation": 1,
        "reactions": 3,
        "designated": 1,
        "poll": 1,
        "affirm": 1,
        "overturned": 5,
        "strictly": 2,
        "overturning": 1,
        "affirmingna": 1,
        "who": 1,
        "then": 6,
        "new": 1,
        "initial": 1,
        "same": 1,
        "original": 1,
        "rulingnan": 1,
        "bearing": 1,
        "interpretation": 1,
        "gamestatenany": 1,
        "candidate": 1,
        "saying": 2,
        "judgeelections": 1,
        "there": 2,
        "candidacies": 2,
        "put": 2,
        "forward": 2,
        "whose": 1,
        "both": 1,
        "becomes": 1,
        "once": 1,
        "candidacy": 1,
        "initiating": 1,
        "ties": 1,
        "broken": 1,
        "earliest": 1,
        "weeknif": 1,
        "retains": 1,
        "positionnnn": 1,
        "nactions": 1,
        "performed": 2,
        "done": 2,
        "appropriate": 1,
        "unambiguously": 1,
        "action": 15,
        "takennwhen": 1,
        "defining": 1,
        "where": 1,
        "intention": 2,
        "provide": 1,
        "perform": 3,
        "making": 1,
        "provision": 1,
        "method": 2,
        "exist": 1,
        "sent": 1,
        "disclaiming": 1,
        "nwhenever": 1,
        "performs": 1,
        "modify": 1,
        "information": 2,
        "generally": 2,
        "tracked": 1,
        "make": 1,
        "reasonable": 1,
        "effort": 1,
        "track": 1,
        "outcome": 1,
        "generallyagreedupon": 1,
        "applicable": 1,
        "locations": 1,
        "else": 2,
        "delegate": 1,
        "tracking": 1,
        "believes": 1,
        "fulfilled": 1,
        "react": 1,
        "indicate": 1,
        "thisnnn": 1,
        "randomness": 1,
        "nwhen": 1,
        "randomisation": 2,
        "concerned": 1,
        "resolved": 3,
        "trusted": 1,
        "fair": 1,
        "accessible": 1,
        "soon": 1,
        "possiblenwhen": 1,
        "determine": 2,
        "random": 10,
        "chance": 3,
        "resolve": 3,
        "next": 1,
        "act": 1,
        "before": 2,
        "involving": 2,
        "result": 1,
        "triggering": 1,
        "event": 2,
        "nonrandom": 1,
        "nonoptional": 1,
        "elements": 1,
        "placenfor": 1,
        "instance": 1,
        "receives": 1,
        "item": 11,
        "optional": 1,
        "special": 1,
        "trait": 3,
        "randomly": 1,
        "applied": 1,
        "receive": 2,
        "attribute": 2,
        "determined": 2,
        "until": 1,
        "determinednnn": 1,
        "choices": 1,
        "deliberately": 1,
        "select": 1,
        "values": 4,
        "rulesdefined": 1,
        "intending": 1,
        "use": 1,
        "those": 1,
        "best": 1,
        "ability": 1,
        "actionnif": 1,
        "selected": 1,
        "some": 1,
        "necessary": 2,
        "discard": 1,
        "valid": 1,
        "specifications": 1,
        "attempt": 1,
        "substantially": 1,
        "similar": 2,
        "goal": 1,
        "obtaining": 1,
        "different": 1,
        "consensus": 1,
        "preponderance": 1,
        "evidence": 1,
        "exists": 1,
        "finds": 1,
        "thing": 1,
        "attempts": 1,
        "first": 1,
        "deemed": 1,
        "invalid": 1,
        "affected": 1,
        "gamestatennn": 1,
        "dice": 3,
        "rolls": 4,
        "requires": 4,
        "selection": 2,
        "ndk": 2,
        "nonnegative": 1,
        "integer": 2,
        "n": 6,
        "positive": 1,
        "k": 2,
        "ksided": 2,
        "diennif": 1,
        "produces": 2,
        "sum": 3,
        "die": 1,
        "independent": 2,
        "selections": 1,
        "integers": 1,
        "uniform": 1,
        "distribution": 1,
        "zero": 1,
        "zeronif": 1,
        "roll": 2,
        "target": 3,
        "x": 2,
        "1dk": 1,
        "meet": 1,
        "exceed": 1,
        "abbreviated": 2,
        "example": 1,
        "3nnn": 1,
        "items": 5,
        "nitems": 1,
        "entities": 1,
        "owned": 2,
        "stored": 1,
        "inventory": 1,
        "owner": 1,
        "cannot": 1,
        "available": 1,
        "nonplayer": 1,
        "destroyednitems": 1,
        "properties": 1,
        "grouped": 1,
        "together": 1,
        "classesnfor": 1,
        "entity": 4,
        "gain": 1,
        "created": 1,
        "entitys": 4,
        "possession": 3,
        "grant": 1,
        "create": 1,
        "lose": 1,
        "destroyed": 1,
        "revoke": 1,
        "destroy": 1,
        "possessionnreputable": 1,
        "trade": 1,
        "inventories": 1,
        "consent": 1,
        "trading": 1,
        "partiesnnote": 1,
        "proven": 1,
        "very": 1,
        "useful": 1,
        "abstraction": 1,
        "nomics": 1
      }
    }
  }
];
